/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOAVERAGE
#define ROOAVERAGE

#include <memory>
#include <vector>

#include "RooAbsReal.h"
#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooListProxy.h"

#include "RooEffHistProd.h"

class RooEffHistProd;

class RooAverage : public RooAbsReal {
public:
   RooAverage() {} ; 
   RooAverage(const char *name, const char *title, 
              const RooArgList& heights, RooEffHistProd& effProd,
              RooRealVar& observable);
   RooAverage(const RooAverage& other, const char* name=0) ;

   virtual TObject* clone(const char* newname) const
   {
      return new RooAverage(*this,newname);
   }

   virtual ~RooAverage();
   
protected:
   
   Double_t evaluate() const;
   
private:

   RooRealProxy _observable;
   RooRealProxy _shape;
   mutable RooRealProxy* _integral;
   
   RooListProxy _values;

   ClassDef(RooAverage,1) // Your description goes here...
};

#endif
