/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOAVERAGE
#define ROOAVERAGE

#include "RooAbsReal.h"
#include "RooSetProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooAverage : public RooAbsReal {
public:
   RooAverage() {} ; 
   RooAverage(const char *name, const char *title, const RooArgSet& vars);
   RooAverage(const RooAverage& other, const char* name=0) ;

   virtual TObject* clone(const char* newname) const
   {
      return new RooAverage(*this,newname);
   }

   inline virtual ~RooAverage() { }
   
protected:
   
   Double_t evaluate() const;
   
private:

   RooSetProxy _vars;
      
   ClassDef(RooAverage,1) // Your description goes here...
};

#endif
