/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooCalibratedDilution.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooCalibratedDilution) 

//_____________________________________________________________________________
RooCalibratedDilution::RooCalibratedDilution(const char *name, const char *title,
                                             RooAbsReal& _p0, RooAbsReal& _p1,
                                             RooAbsReal& _w, RooAbsReal& _w_average)
   : RooAbsReal(name, title), p0("p0","p0", this, _p0), p1("p1","p1", this, _p1),
     w("w", "w", this, _w), w_average("w_average", "w_average", this, _w_average)
{
}

//_____________________________________________________________________________
RooCalibratedDilution::RooCalibratedDilution(const RooCalibratedDilution& other, const char* name)
   : RooAbsReal(other, name), p0("p0", this, other.p0), p1("p1", this,other.p1),
     w("w", this, other.w), w_average("w_average", this, other.w_average)
{ 
} 

//_____________________________________________________________________________
Double_t RooCalibratedDilution::evaluate() const
{ 
   return 1 - 2 * (p0 + p1 * (w - w_average));
} 
